### ISSUE TITLE
YO WTF THE SITES DOWN

### ISSUE THREAD

**Issue by jxjshaw** [lchack/lchack.org#1]
![hangover-ken-jeong-chow-8DDm8vcPn3zJm](https://media4.giphy.com/media/8DDm8vcPn3zJm/giphy.gif)

**Comment by milescrabill** [comment]
![wth](http://i.giphy.com/3o7ZeF03Nfo2k1G3de.gif)

**Comment by milescrabill** [comment]
Fixed :+1:
